schema: "classroom50/repo-config/v1"
classroom: "etc5523"
assignment: "assignment-3"
owner:
  username: "shro-ots"
  id: 195046976
  accepted_at: "2026-09-30T06:18:09Z"
source:
  owner: "ETC5523-2026"
  owner_id: 265932295
  repo: "assignment-3"
  branch: "main"
